<?php

/**
 * @file
 * Code of the eMindHub request submission feature.
 */

include_once 'emh_request_submission.inc';
include_once 'emh_request_submission.block.inc';
include_once 'emh_request_submission.form.inc';
include_once 'emh_request_submission.mail.inc';

/**
 * Implements hook_webform_submission_access().
 */
function emh_request_submission_webform_submission_access($node, $submission, $op = 'view', $account = NULL) {
  switch ($op) {
    case 'view':
      return emh_access_user_can_see_full_answer($node->nid, $submission->sid);

    case 'edit':
      return emh_request_submission_edit_access_callback($node, $submission);

    case 'flag':
      return emh_access_user_can_see_full_answer($node->nid, $submission->sid);
  }
}
