<?php
/**
* @file
* Code for eMindHub FAQ feature.
*/

/**
 * Implements hook_views_api().
 */
function emh_faq_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'emh_faq') . '/views',
  );
}

function emh_faq_reset_views() {
  module_load_include('inc', 'emh_faq', 'views/emh_faq.views_default');
  $default_views = emh_faq_views_default_views();
  foreach($default_views as $name => $view) {
    views_revert_view($view);
  }
}
