<?php
/**
 * @file
 * Install file for the wc_payment module.
 */

/**
 * Implements hook_install().
 */
function node_authored_select_install() {
  variable_set('node_authored_select_role', 3);
  variable_set('node_authored_select_node_type', array());
}

/**
 * Implements hook_uninstall().
 */
function node_authored_select_uninstall() {
  variable_del('node_authored_select_role');
  variable_del('node_authored_select_node_type');
}
