<?php

/**
 * @file
 * Code of the eMindHub circle notification feature.
 */

/**
 * Implements hook_og_membership_insert().
 */
function emh_circles_notification_og_membership_insert($og_membership) {
  if ($og_membership->entity_type == 'user') {
    $group = entity_metadata_wrapper($og_membership->group_type, $og_membership->gid);
    $user = user_load($og_membership->etid);
    $node = node_load($og_membership->gid);
    _emh_circles_notification_membership_requested($group, $user, $node);
  }
}

/**
 * When a membership is requested, send an email notification.
 */
function _emh_circles_notification_membership_requested($group, $user, $node) {
  $accounts_uid = _emh_circles_get_group_admins($group);
  $accounts_uid[] = _emh_circles_get_group_manager($group);

  // Remove duplicate users.
  $accounts_uid = array_keys(array_flip($accounts_uid));
  $accounts = user_load_multiple($accounts_uid);

  foreach ($accounts as $account) {
    // Note: should use a queue if there are too many admins.
    rules_invoke_event('_emh_circles_notification_membership_requested', $node, $account, $user);
  }
}
