<?php
/**
* @file
* Code for eMindHub access feature.
*/

function emh_access_author_name( $node ) {

  $access = FALSE;

  // Check node options
  // 0|Display my full name
  // 1|Hide my full name
  $anonymous_mode = field_get_items('node', $node, 'field_anonymous');
  if ($anonymous_mode[0]['value'] == 0) {
    $access = TRUE;
  }

  return $access;
}

function emh_access_author_company( $node ) {

  $access = FALSE;

  // Check node options
  // 0|Display the name
  // 1|Hide the name
  $show_entreprise = field_get_items('node', $node, 'field_show_entreprise');
  if ($show_entreprise[0]['value'] == 0) {
    $access = TRUE;
  }

  return $access;
}
