<?php

/**
 * @file
 * Code of the eMindHub request submission flags feature.
 */

include_once 'emh_request_submission_flags.inc';
include_once 'emh_request_submission_flags.flags.inc';

/**
 * Implements hook_theme().
 */
function emh_request_submission_flags_theme() {
  return array(
    'flag_description' => array(
      'template' => 'flag-description',
      'path' => drupal_get_path('module', 'emh_request_submission_flags') . '/theme',
      'variables' => array(
        'short' => NULL,
        'long' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function emh_request_submission_flags_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'emh_request_submission_flags') . '/views',
  );
}

/**
 * Implements hook_flag_javascript_info_alter().
 */
function emh_request_submission_flags_flag_javascript_info_alter(&$info, $flag) {
  if ($flag->name === 'interesting_answer') {
    $info['newLink'] = $flag->theme($flag->is_flagged($info['contentId']) ? 'unflag' : 'flag', $info['contentId'], array(
      'after_flagging' => FALSE,
      'errors' => $flag->get_errors(),
    ));
  }
}
