<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_help().
 */
function admin_users_help($path, $arg) {
  switch ($path) {
    case 'admin/help#admin_users':
      $output = '';
      $output .= '<p>' . t('User  with id = 1 and the current user are excluded from the output on the
      (<a href="@url">Administration Users page</a>) in order to eliminate the possibility of accidental deletion of
      Super admin and the user himself.', array('@url' => url('admin/people/list'))) . '</p>';
      $output .= '<p>' . t('The module depends on the module Views, it means that the page with the users can be easily
      changed for any site, and bulk operations are easily added with the help of the
      <a href="@rules">Rules</a> module', array('@rules' => 'https://drupal.org/project/rules')) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_views_api().
 */
function admin_users_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'admin_users') . '/views',
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function admin_users_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  $view = $form_state['view'];

  if ($view->name == 'administration_users') {
    // Adding css file for fix padding and margin
    // For exposed "Items per page" element in seven theme.
    $form['#attached']['css'][] = drupal_get_path('module', 'admin_users') . '/css/admin-users.css';
  }
}
