<?php
// $Id: mb.install,v 1.1.2.1 2010/11/27 13:30:52 quiptime Exp $

/**
 * @file
 * Installs, updates, and uninstalls More Buttons.
 */

/**
 * Implements hook_install().
 */
function mb_install() {
  module_load_include('module', 'mb');
  $default_values = mb_default_values();
  variable_set('mb_values', $default_values);
}

/**
 * Implements hook_uninstall().
 */
function mb_uninstall() {
  // Remove variables.
  variable_del('mb_values');
}
