<?php

/**
 * @file
 * Tracking features for EMH website.
 */

// Days before the cookie expires.
const EMH_TRACKING_COOKIE_DURATION = 365;

/**
 * Implements hook_init().
 */
function emh_tracking_init() {

  // Using hook_boot() eats 10% of site performance,
  // so we are setting a cookie with JS in hook_init() only.
  // We need the jQuery.cookie library for anonymous users.
  // Normally, Drupal loads it for authentificated users only,
  // so we have to add it manually.
  // We add the library on every page to allow JS aggregation.
  // It's 961 bytes, @see /misc/jquery.cookie.js.
  drupal_add_library('system', 'jquery.cookie', TRUE);

  // 1. If there is a "r" query parameter:
  // (note that every URL with ?r=TRACKING_KEY is considered as a different page
  // than the original one, so the cache size will increase.
  if ($r = filter_input(INPUT_GET, 'r', FILTER_SANITIZE_STRING)) {

    // 2. If it's alphanumeric:
    if (ctype_alnum($r)) {

      // Normally we don't have to sanitize this.
      $http_referer = $_SERVER['HTTP_REFERER'] ? $_SERVER['HTTP_REFERER'] : '';

      // Prepare our tracking info.
      $tracking_info = json_encode(
        array(
          'r' => $r,
          'h' => $http_referer,
        )
      );

      // Prepare JS.
      // It will check if the cookie 'emh' exists and if not, will create it.
      $cookie = "jQuery(document).ready(function () {
        if (jQuery.cookie('emh') == undefined) {
          jQuery.cookie('emh', '" . $tracking_info . "', { expires: " . EMH_TRACKING_COOKIE_DURATION . ", path: '/' });
        }
      });";

      // Add the JS.
      drupal_add_js(
        $cookie, array(
          'type' => 'inline',
          'scope' => 'footer',
        )
      );
    }
  }
}

/**
 * Implements hook_user_presave().
 */
function emh_tracking_user_presave(&$edit, $account, $category) {

  if ($account->is_new) {

    // If there is a tracking cookie:
    if (isset($_COOKIE['emh'])) {

      $tracking_info = json_decode($_COOKIE['emh'], TRUE);

      // Validate and record the tracking key.
      if (isset($tracking_info['r']) && ctype_alnum($tracking_info['r'])) {
        $edit['field_tracking_key'][LANGUAGE_NONE][0]['value'] = $tracking_info['r'];
      }
      // Record the referer URL.
      $http_referer = check_url(stripslashes($tracking_info['h']));
      if (isset($tracking_info['h']) && valid_url($http_referer, TRUE)) {
        $edit['field_tracking_referer'][LANGUAGE_NONE][0]['url'] = $http_referer;
      }
    }
  }
}
