<?php

function emh_freetrial_menu() {
  $items = array();
  $items['freetrial'] = array(
    'title' => t('Free trial offer'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('emh_freetrial_form'),
    'access callback' => TRUE
  );
	$items['admin/config/freetrial'] = array(
    'title' => 'Free trial',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('emh_freetrial_form_settings'),
    'description' => "Enter email to get free trial requests.",
    'access callback' => 'user_access',
    'access arguments' => array('access administration menu'),
  );
  return $items;
}


function emh_freetrial_form($form, &$form_state) {

	$form['emh_baseline'] = array(
    '#markup' => '<p class="emh-title-baseline">' . t('Ask for a free trial') . '<br /><strong>' . t('Fill in this form, we will get back at you within 24h!') . '</strong></p>',
    '#weight' => '-1000', // First !
  );

	$form['firstname'] = array(
		'#title' => t('Your first name'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);

	$form['lastname'] = array(
		'#title' => t('Your last name'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);

	$form['entreprise'] = array(
		'#title' => t('Your organisation / company'),
		'#type' => 'textfield',
		//'#required' => TRUE,
	);

	$form['position'] = array(
		'#title' => t('Your position'),
		'#type' => 'textfield',
		//'#required' => TRUE,
	);

	$form['phone'] = array(
		'#title' => t('Your phone'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);

	$form['mail'] = array(
		'#title' => t('Your email'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);

	$form['message'] = array(
		'#title' => t('Your message'),
		'#type' => 'textarea',
		'#required' => TRUE,
	);

	$form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
  );

	$form['#submit'][] = 'emh_freetrial_form_submit';

	return $form;

	// echo '<pre>' . print_r($form, TRUE) . '</pre>';

}

function emh_freetrial_form_submit($form, &$form_state) {
	emh_freetrial_mail_send($form_state['values']);
}

/**
 * Implement hook_mail().
 * @deprecated? maybe, needs checks
 */
function emh_freetrial_mail($key, &$message, $params) {
  global $user;
  $options = array(
    'langcode' => $message['language']->language,
  );

  switch ($key) {
    case 'emh_freetrial_form_submit':
      $message['subject'] = t('[@site-name] New free trial request', array('@site-name' => variable_get('site_name', 'Drupal')), $options);
      $message['body'][] = t('Hello,');
      $message['body'][] = t('A new free trial access has been requested by') . ' <strong>' . check_plain($params['firstname']) . ' ' . check_plain($params['lastname']) . '</strong>';
      if (!empty($params['enterprise'])) $message['body'][] = t('Organisation') . ': <strong>' . check_plain($params['enterprise']) . '</strong>';
      if (!empty($params['position'])) $message['body'][] = t('Position') . ': <strong>' . check_plain($params['position']) . '</strong>';
      if (!empty($params['phone'])) $message['body'][] = t('Phone') . ': <strong>' . check_plain($params['phone']) . '</strong>';
      if (!empty($params['mail'])) $message['body'][] = t('Email') . ': <strong>' . check_plain($params['mail']) . '</strong>';
      if (!empty($params['message'])) $message['body'][] = t('Message') . ': <strong>' . check_plain($params['message']) . '</strong>';
      break;
  }
}


/**
 * Sends an e-mail.
 *
 */
function emh_freetrial_mail_send($form_values) {

  $module = 'emh_freetrial';
  $key = 'emh_freetrial_form_submit';
  $to = variable_get('emh_freetrial_form_email_id');
  $from = variable_get('site_mail', 'contact@emindhub.com');
  $params = $form_values;
  $language = language_default();
  $send = TRUE;
  $result = drupal_mail($module, $key, $to, $language, $params, $from, $send);

  if ($result['result'] == TRUE) {
    drupal_set_message(t('Your request has been sent.'));
  } else {
    drupal_set_message(t('There was a problem sending your message and it was not sent. Please try again or contact the administrators.'), 'error');
  }

}


function emh_freetrial_form_settings() {
  $form['emh_freetrial_form_email_id'] = array(
    '#type'             => 'textfield',
    '#title'            => t('Enter Email ID.'),
    '#default_value'    => variable_get('emh_freetrial_form_email_id'),
    '#description'      => t('Enter a email id to receive feedback mail'),
  );
  return system_settings_form($form);
}
