<?php
/**
 * @file
 * Code for the eMindHub Survey module installation.
 */

/**
 * Implements hook_enable
 */
function emindhub_survey_enable() {
  emindhub_survey_update_7001();
}

/**
 * Force module weight for hook_form_alter execution
 */
function emindhub_survey_update_7001() {
  db_update('system')
  ->fields(array('weight' => 1))
  ->condition('type', 'module')
  ->condition('name', 'emindhub_survey')
  ->execute();
}
