<?php

/**
 * @file
 * Code for EMH Smart Mobility feature.
 */

include_once 'emh_smartmobility.block.inc';
include_once 'emh_smartmobility.pages.inc';

/**
 * Implements hook_form_alter().
 */
function emh_smartmobility_form_alter(&$form, &$form_state, $form_id) {
  global $base_url;
  switch ($form_id) {
    case 'user_login':
    case 'user_login_block':
      unset($form['#action']);
      $form['#action'] = url('<front>', array(
          'base_url' => $base_url,
          'absolute' => TRUE,
          'language' => (object)array('language' => FALSE)
      ));
      break;
  }
}


/**
 * Implements hook_theme().
 */
function emh_smartmobility_theme() {
  return array(
    'emh_smartmobility_page' => array(
      'template' => 'emh-smartmobility--page',
      'path' => drupal_get_path('module', 'emh_smartmobility') . '/theme',
    ),
    'emh_smartmobility_block_persona' => array(
      'template' => 'block--emh-smartmobility--persona',
      'path' => drupal_get_path('module', 'emh_smartmobility') . '/theme',
      'variables' => array(
        'title' => NULL,
        'content' => NULL,
       ),
    ),
    'emh_smartmobility_block_partners' => array(
      'template' => 'block--emh-smartmobility--partners',
      'path' => drupal_get_path('module', 'emh_smartmobility') . '/theme',
      'variables' => array(
        'title' => NULL,
        'content' => NULL,
       ),
    ),
  );
}

/**
 * Implements hook_custom_theme().
 */
function emh_smartmobility_custom_theme() {
  if (arg(0) == 'smart-mobility' && !arg(1)) {
    return 'smartmobility';
  }
}

/**
 * Implements hook_menu().
 */
function emh_smartmobility_menu() {
  $items = array();

  $items['smart-mobility'] = array(
    'title' => 'Smart Mobility',
    'page callback' => 'emh_smartmobility_page',
    'access callback' => 'user_is_anonymous',
  );

  return $items;
}
