<?php
/**
 * @file
 * Installation hooks for the virality features.
 */

/**
 * Implements hook_schema().
 */
function emh_virality_schema() {
  $schema = array();

  $schema['emh_invitation'] = array(
    'description' => 'Stores invitations made by the users to unregistered people',
    'fields' => array(
      'invitation_id' => array(
        'description' => 'Invitation uniq identifier',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'created_at' => array(
        'description' => 'Creation timestamp of the invitation',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'updated_at' => array(
        'description' => 'Update timestamp of the invitation',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'referrer_id' => array(
        'description' => 'ID of the referrer user',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'referral_id' => array(
        'description' => 'ID of the referral user',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
      ),
      'referral_mail' => array(
        'description' => 'Email of the referral user',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ),
      'request_id' => array(
        'description' => 'Request ID (nid) the invitation is linked to',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
      ),
      'status' => array(
        'description' => 'Status of the invitation (pending, validated, ...)',
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ),
      'message' => array(
        'description' => 'Personal message to sponsor a request.',
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
       ),
    ),
    'primary key' => array('invitation_id'),
    'unique keys' => array(
      'unique_invitation' => array('referrer_id', 'referral_mail'),
    ),
    //'indexes' => array(),
  );

  return $schema;
}

function emh_virality_schema_alter(&$schema) {
  
}

/**
 * Implements hook_enable().
 */
function emh_virality_enable() {
  emh_virality_update_7001();
  variable_set('emh_virality_business_invitation_reward', 50);
  variable_set('emh_virality_expert_invitation_reward', 50);
}

/**
 * Implements hook_uninstall().
 */
function emh_virality_uninstall() {
  variable_del('emh_virality_business_invitation_reward');
  variable_del('emh_virality_expert_invitation_reward');
}

/**
 * Extend access to the Invitations tab to authentificated users + Invitations history to webmasters.
 */
function emh_virality_update_7001() {
  user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, array('invite experts'));
  user_role_grant_permissions(3, array('view others invitations history')); // Administrator role
  user_role_grant_permissions(6, array('view others invitations history')); // Webmaster role
}

/**
 * Update invitation form block by removing PHP code.
 */
function emh_virality_update_7002() {
  $module = 'emh_virality';
  $delta = 'invitation_form';
  db_update('block')
    ->fields(array(
      'visibility' => '1',
      'pages' => "user/*/invitations\ninvitations",
    ))
    ->condition('module', $module)
    ->condition('delta', $delta)
    ->execute();
}

function emh_virality_update_7003() {
 if(!db_field_exists('emh_invitation', 'message')) {
   $spec = array(
    'description' => 'Personal message to sponsor a request.',
    'type' => 'text',
	  'size' => 'big',
    'not null' => FALSE,
  );
  db_add_field('emh_invitation', 'message', $spec);
 }
}