<?php
/**
 * @file
 * Installation hooks for the emh_user_profile_purchase module.
 */


/**
 * Implements hook_install().
 */
function emh_user_profile_purchase_enable() {
  variable_set('emh_user_profile_purchase_amount', 100);
}

/**
 * ADD: VBO Purchase profile permissions.
 */
function emh_user_profile_purchase_update_7101() {
  // Authentificated user
  user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, array('execute emh_user_profile_purchase_action'));
}
