<?php
define("c_szClickToZoom",               t("Click to zoom"));

//////////////////
//Textes anglais:
define("c_szHaveQuestion",              t("You have a request?"));
define("c_szViewUsrProfile",            t("View user profile."));
define("c_szYourSearch",                t("Type your search, keywords..."));
define("c_szBackHome",                  t("Back home"));
define("c_szYouHave",                   t("You have"));
define("c_szAnAsk",                     t("a request"));
define("c_szSignUp",                    t("Sign-up"));
define("c_szUseEmhServices",            t("as a client and use emindhub's services"));
define("c_szAnExpertise",               t("an expertise"));
define("c_szAnswerAsks",                t("as an expert and answer the requests"));
define("c_szKnowMore",                  t("More about us?"));
define("c_szSearch",                    t("Search"));
define("c_szGo",                        t("GO!"));
define("c_szLogin",                     t("Login"));
define("c_szRegister",                  t("Register"));
define("c_szLogout",                    t("Logout"));
define("c_szMobilizeExperts",           t("How to mobilize the experts?"));
define("c_szAskRealTime",               t("Ask a question online and get responses from experts"));
define("c_szCompeteExperts",            t("Request for service propositions to innovate or solve a problem"));
define("c_szBuildSurvey",               t("Create a survey to find an expert profile"));
define("c_szOurEngagements",            t("WHY USE EMINDHUB ?"));
define("c_szRapidity",                  t("Rapidity"));
define("c_szReactivityCommunity",       t(" ensures a quick response with its large network of"));
define("c_szConnectedExperts",          t("connected experts"));
define("c_szSecurity",                  t("Security"));
define("c_szAllowChoose",               t(" allows you to choose"));
define("c_szExpertCircle",              t(" circles of"));
define("c_szAskInConfidence",           t(" trustworthy experts"));
define("c_szRegisterKnowMore",          t("Register to know more"));
define("c_szQuality",                   t("Quality"));
define("c_szReliesOn",                  t(" is based on"));
define("c_szReferentExperts",           t(" lead experts"));
define("c_szContributionsQuality",      t(" who guarantee the quality of the responses"));
define("c_szTextBanniere",              t("GET ONLINE ACCESS TO %sTHE 1ST GLOBAL NETWORK OF EXPERTS%s IN AEROSPACE"));
define("c_szWhoAreExperts",             t("ABOUT EXPERTS"));
define("c_szExperimentedPro",           t("Experienced professionals, active retirees, researchers, students…"));
define("c_szInYourNetwork",             t("Find the experts you need in the emindhub's network"));
define("c_szWithEmindhub",              t("With emindhub,"));
define("c_szYouOrganize",               t("address your request to one or several circles of experts"));
define("c_szWorldDb",                   t("Our worldwide database of experts"));
define("c_szAll",                       t("ALL"));
define("c_szSponsoredByPeers",          t("experts sponsored by their peers"));
define("c_szSponsored",                 t("SPONSORED"));
define("c_szYourPartnersAndEmployees",  t("Your employees and your business partners"));
define("c_szYourNetwork",               t("YOUR ACTIVE"));
define("c_szActive",                    t("NETWORK"));
define("c_szOldsContributors",          t("People who left your organization"));
define("c_szYours",                     t("YOUR"));
define("c_szAlumnis",                   t("ALUMNI"));
define("c_szOnDemandCircles",           t("Circles created on demand"));
define("c_szYouCircles",                t("YOUR CUSTOMISED"));
define("c_szPrivates",                  t("SELECTION"));
define("c_szExperts",                   t("EXPERTS"));
define("c_szAllExperts",                t("THE EXPERTS"));
define("c_szSearchTerms",               t("Enter your search terms"));
define("c_szSearchKeywords",            t("Key words for your search…"));
define("c_szLearnMore",                 t("Do you want to learn more?"));
define("c_szLeaveMsg",                  t("Leave us a message, we will get back at you within 24h!"));
define("c_szRequiredField",             t("Required fields"));
define("c_szAllRequiredFields",         t("All fields are required"));
define("c_szAnswerChallenge",           t("Answer a challenge"));
define("c_szPublicationDt",             t("Publication date:"));
define("c_szNumResponses",              t("Number of responses:"));
define("c_szCreateWorkgroup",           t("Create a working group"));
define("c_szChooseFile",                t("Choose a file"));
define("c_szAnswerQuestion",            t("Answer a question"));
define("c_szDescription",               t("Description:"));
define("c_szAnswerExpertCall",          t("Answer a survey"));
define("c_szBusinessRegister",          t("Register as a client"));
define("c_szCreateAccount",             t("Create your account "));
define("c_szNoTime",                    t("for free in no time"));
define("c_szExpertRegister",            t("Register as an expert"));
define("c_szAddQuestion",               t("Ask %sa question%sLearn more%s"));
define("c_szCreateChallenge",           t("Start %sa challenge%sLearn more%s"));
define("c_szFindExpert",                t("Create %sa survey%sLearn more%s"));
define("c_szEmindhub",                  t("emindhub"));
define("c_szLoginToEmh",                t("Login to emindhub:"));
define("c_szRegisterToEmh",             t("Register form to emindhub:"));
define("c_szSignIn",                    t("Sign-in "));
define("c_szInAMinute",                 t("in 1 minute"));
define("c_szStart",                     t("and start!"));
define("c_szSeeker",                    t("As a client"));
define("c_szExpert",                    t("As an expert"));
define("c_szSubmitted",                 t("Submitted by:"));
