<?php
/**
* @file
* A module that would allow users to add fields
* Created by: Andrei Ghenoiu
* Date: 8/24/12
* Resources from: http://www.pensamientosdivergentes.net/blog/modifying-contact-form-drupal-how-add-field, 			http://www.metaltoad.com/blog/how-add-field-drupal-contact-form
*/

function emh_freetrial_help($path, $arg) {
	switch($path) {
		case "admin/help#emh_freetrial":
			return '<p>'. t("allows users to add new fields to the site wide contact form - at the moment there is no option to configure it").'</p>';
			break;
	}
}


function emh_freetrial_menu() {
  $items = array();

  $items['freetrial'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Free trial offer', //page title
    'description' => 'A form to mess around with.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('emh_freetrial_form'), //put the name of the form here
    'access callback' => TRUE
  );

	$items['admin/emh_freetrial/settings'] = array(
    'title' => 'Enter Email ID',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('emh_freetrial_form_settings'),
    'description' => "Enter Email ID to get drupal feedback message.",
    'access callback' => 'user_access',
    'access arguments' => array('access administration menu'),
  );

  return $items;

}


function emh_freetrial_form($form, &$form_state) {

	$form['emh_baseline'] = array(
    '#markup' => '<p class="emh-title-baseline">' . t('Ask for a free trial') . '<br /><strong>' . t('Fill in this form, we will get back at you within 24h!') . '</strong></p>',
    '#weight' => '-1000', // First !
  );

	$form['civility'] = array(
		// '#title' => t('Civility'),
		'#title_display' => 'invisible',
		'#type' => 'select',
		'#options' => array(t('Mr'), t('Mrs'), t('Ms')),
		'#required' => TRUE,
	);

	$form['firstname'] = array(
		// '#title' => t('Your first name'),
		'#title_display' => 'invisible',
		'#type' => 'textfield',
		'#required' => TRUE,
		'#attributes' => array(
			'placeholder' => t('Your first name'),
		),
	);

	$form['lastname'] = array(
		// '#title' => t('Your last name'),
		'#title_display' => 'invisible',
		'#type' => 'textfield',
		'#required' => TRUE,
		'#attributes' => array(
			'placeholder' => t('Your last name'),
		),
	);

	$form['entreprise'] = array(
		// '#title' => t('Your organisation'),
		'#title_display' => 'invisible',
		'#type' => 'textfield',
		//'#required' => TRUE,
		'#attributes' => array(
			'placeholder' => t('Your organisation'),
		),
	);

	$form['position'] = array(
		// '#title' => t('Your organisation'),
		'#title_display' => 'invisible',
		'#type' => 'textfield',
		//'#required' => TRUE,
		'#attributes' => array(
			'placeholder' => t('Your position'),
		),
	);

	$form['phone'] = array(
		// '#title' => t('Your phone'),
		'#title_display' => 'invisible',
		'#type' => 'textfield',
		'#required' => TRUE,
		'#attributes' => array(
			'placeholder' => t('Your phone'),
		),
	);

	$form['mail'] = array(
		'#title_display' => 'invisible',
		'#type' => 'textfield',
		'#required' => TRUE,
		'#attributes' => array(
			'placeholder' => t('Your email'),
		),
	);

	$form['message'] = array(
		'#title_display' => 'invisible',
		'#type' => 'textarea',
		'#required' => TRUE,
		'#attributes' => array(
			'placeholder' => t('Your message'),
		),
	);

	// $form['name']['#required'] = FALSE;
	// $form['name']['#type'] = 'hidden';
	//
	// $form['cid']['#type'] = 'hidden';
	//
	// $form['subject']['#required'] = FALSE;
	// $form['subject']['#type'] = 'hidden';
	//
	// $form['copy']['#type'] = 'hidden';

	$form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
  );

	$form['#submit'][] = 'emh_freetrial_form_submit';

	// $form['#token'] = NULL;

	// $order = array('name', 'mail', 'message', 'actions');
	//
	// foreach ($order as $key => $field) {
	// 	$form[$field]['#weight'] = $key;
	// }

	return $form;

	// echo '<pre>' . print_r($form, TRUE) . '</pre>';

}


// function emh_freetrial_form_validate($form, &$form_state) {
// }

function emh_freetrial_form_submit($form, &$form_state) {
	emh_freetrial_mail_send($form_state['values']);
}

/**
 * Implement hook_mail().
 *
 */
function emh_freetrial_mail($key, &$message, $params) {
  global $user;
  $options = array(
    'langcode' => $message['language']->language,
  );

  switch ($key) {
    case 'emh_freetrial_form_submit':
      $message['subject'] = t('A new Feedback addded in site @site-name', array('@site-name' => variable_get('site_name', 'Drupal')), $options);
      $message['body'][] = t('@name added the following feedback:', array('@name' => $user->name), $options);
      $message['body'][] = check_plain($params['message']);
      break;
  }
}


/**
 * Sends an e-mail.
 *
 */
function emh_freetrial_mail_send($form_values) {
  $module = 'emh_freetrial';
  $key = 'emh_freetrial_form_submit';
  $to = variable_get('emh_freetrial_form_email_id');
  $from = variable_get('site_mail', 'admin@example.com');
  $params = $form_values;
  $language = language_default();
  $send = TRUE;
  $result = drupal_mail($module, $key, $to, $language, $params, $from, $send);

  if ($result['result'] == TRUE) {
    drupal_set_message(t('Your message has been sent.'));
  }
  else {
    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  }

}


function emh_freetrial_form_settings() {
  $form['emh_freetrial_form_email_id'] = array(
    '#type'             => 'textfield',
    '#title'            => t('Enter Email ID.'),
    '#default_value'    => variable_get('emh_freetrial_form_email_id'),
    '#description'      => t('Enter a email id to receive feedback mail'),
  );
  return system_settings_form($form);
}

// function emh_freetrial_mail(&$message) {
// 	if ($message['id'] == 'contact_page_mail') {
// 		$message['id'] = 'custom_contact_mail'; // Important, otherwise suject will be overriden
// 	 	$message['subject'] = $message['subject'].' '. t('From').' '.$message['from'];
// 	 	$message['body'][] = t('From - ').' '.$message['params']['firstname'].' '.$message['params']['lastname'];
// 		$message['body'][] = t('Phone').': '.$message['params']['phone'];
// 		$message['body'][] = t('Organisation / Company').': '.$message['params']['entreprise'];
// 	}
// }
