<?php
/**
 * @file
 * Installation hooks for the EMH Notification module.
 */

/**
 * Delete old notification rule and add variable for the delay between moderation and notification.
 */
function emh_request_notification_update_7001() {
  if ($rules_config = rules_config_load('rules_emh_request_send_notification_email')) {
    $rules_config->delete();
  }
  variable_set('emh_request_notification_notify_delay', 30);
}
