<?php

/**
 * @file
 * Ethereum web3 library.
 */

/**
 * Implements hook_libraries_info().
 */
function ethereum_web3_libraries_info() {
  $libraries['web3'] = array(
    'name' => 'web3.js',
    'vendor url' => 'https://github.com/ethereum/web3.js/',
    'download url' => 'https://github.com/ethereum/web3.js/releases',
    'version arguments' => array(
      'file' => 'dist/web3.js',
      'pattern' => '/"version": "(1.0.0-beta\.[0-9]+)",/',
      'lines' => 50000,
    ),
    'files' => array(
      'js' => array('dist/web3.min.js'),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_menu().
 */
function ethereum_web3_menu() {
  $items = array();

  $items['admin/config/ethereum/web3'] = array(
    'title' => 'Web3.js',
    'description' => 'Web3.js settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ethereum_web3_admin_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'ethereum_web3.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function ethereum_web3_init() {

  if (_ethereum_user_ready()) {
    // Try to load a local Web3.js.
    $library = libraries_load('web3');
    if ($library && !empty($library['loaded'])) {
      // Pass Web3.js settings to JS.
      $settings = array(
        'network' => variable_get('ethereum_web3_network'),
        'messages_selector' => variable_get('ethereum_web3_messages_selector'),
        'messages_base' => variable_get('ethereum_web3_messages_base'),
        'messages_status' => variable_get('ethereum_web3_messages_status'),
        'messages_warning' => variable_get('ethereum_web3_messages_warning'),
        'messages_error' => variable_get('ethereum_web3_messages_error'),
      );
      drupal_add_js(array('ethereum_web3' => $settings), 'setting');
      // Init Web3.js.
      drupal_add_js(
        drupal_get_path('module', 'ethereum_web3') . '/js/ethereum_web3.js',
        array(
          'type' => 'file',
          'scope' => 'footer',
          'weight' => '-20',
        )
      );
    }
    else {
      watchdog('ethereum_web3', 'Web3.js not found locally', array(), WATCHDOG_ERROR);
    }
  }
}

function stringEndsWith($end, $whole){
  return (strpos($whole, $end, strlen($whole) - strlen($end)) !== false);
}

function web3_check_transaction($tx_hash, $from_uid, $to_uid, $contract_name, $price) {
  require 'ethereum-php/ethereum.php';
  $provider = explode(':', str_replace('http://', '', variable_get('ethereum_web3_node')));
  $ethereum = new Ethereum($provider[0], intval($provider[1]));
  $tx = $ethereum->eth_getTransactionByHash($tx_hash);
  $from = $tx->from;
  $tier = $tx->to;
  $to = '0x'.substr($tx->input, 32+2, 40);
  $user_from = user_load($from_uid);
  $contract = _ethereum_smartcontract_get($contract_name);
  $address = $contract->ethereum_address->value();
  $to_user = user_load($to_uid);
  if (strcasecmp($from, $user_from->ethereum_address['und'][0]['ethereum_address']) != 0)
    return t('Your ethereum address do not match '.$from. " / ($from_uid)" . $user_from->ethereum_address['und'][0]['ethereum_address']);
  if (strcasecmp($to,$to_user->ethereum_address['und'][0]['ethereum_address']) != 0)
    return t('Expert ethereum address do not match '.$to. " / ($to_uid)" . $to_user->ethereum_address['und'][0]['ethereum_address']);
  if (strcasecmp($tier,$address) != 0)
    return t('Contract address do not match '.$tier. ' / ' . $address);
  if (! stringEndsWith( dechex(intval($price)), $tx->input ))
    return t('The price does not match '. dechex(intval($price)) . ' / ' . $tx->input);
  return '';
}
