<?php
/**
* @file
* Code for eMindHub circles feature.
*/

/**
 * Implements hook_views_api().
 */
function emh_circles_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'emh_circles') . '/views',
  );
}

function emh_circles_reset_views() {
  module_load_include('inc', 'emh_circles', 'views/emh_circles.views_default');
  $default_views = emh_circles_views_default_views();
  foreach($default_views as $name => $view) {
    views_revert_view($view);
  }
}

/**
 * Implements hook_node_access().
 */
function emh_circles_node_access($node, $op, $account) {
  if ($op == 'view') {
    switch ($node->type) {
      case 'circle':
        if (user_is_anonymous()) return NODE_ACCESS_DENY;
        break;
      default:
        break;
    }
  }
  return NODE_ACCESS_IGNORE;
}

function _emh_circles_check_user_is_referentmember_of_groups($uid, $gids) {
  $roleID = db_select('og_role', 'og')
            ->condition('name', 'Referent member', '=')
            ->distinct()
            ->fields('og', array('rid'))
            ->execute();
  $roleID = $roleID->fetchAssoc();

  if (!empty($roleID)) {
    foreach ($gids as $gid) {
      $isReferentMember = db_select('og_users_roles', 'og')
                ->condition('gid', $gid, '=')
                ->condition('uid', $uid, '=')
                ->condition('rid', $roleID['rid'], '=')
                ->distinct()
                ->fields('og', array('rid'))
                ->execute();
      $isReferentMember = $isReferentMember->fetchAssoc();
      if (!empty($isReferentMember)) {
        return TRUE;
      }
    }
  }
  return FALSE;
}

function _emh_circles_check_user_is_adminmember_of_groups($uid, $gids) {
  $roleID = db_select('og_role', 'og')
            ->condition('name', 'administrator member', '=')
            ->distinct()
            ->fields('og', array('rid'))
            ->execute();
  $roleID = $roleID->fetchAssoc();

  if (!empty($roleID)) {
    foreach ($gids as $gid) {
      $isAdminMember = db_select('og_users_roles', 'og')
                ->condition('gid', $gid, '=')
                ->condition('uid', $uid, '=')
                ->condition('rid', $roleID['rid'], '=')
                ->distinct()
                ->fields('og', array('rid'))
                ->execute();
      $isAdminMember = $isAdminMember->fetchAssoc();
      if (!empty($isAdminMember)) {
        return TRUE;
      }
    }
  }
  return FALSE;
}

function _emh_circles_check_user_is_admin_of_groups($uid, $gids) {
  foreach ($gids as $gid) {
    $result = db_select('node', 'n')
              ->condition('nid', $gid, '=')
              ->distinct()
              ->fields('n', array('uid'))
              ->execute();
    $node_uid = $result->fetchAssoc();
    if ($node_uid['uid'] == $uid) {
      return TRUE;
    }
  }
  return FALSE;
}
