<?php
/**
 * @file
 * Installation hooks for the EMH Users module.
 */


/**
* Implements hook_enable
*/
function emh_users_enable() {
  emh_users_update_7001();
}


/**
 * Force module weight for hook_form_alter execution
 */
function emh_users_update_7001() {
  db_update('system')
  ->fields(array('weight' => 1))
  ->condition('type', 'module')
  ->condition('name', 'emh_users')
  ->execute();
}
