<?php
/**
 * @file
 * Code for eMindHub Profile Complete feature for Experts.
 */

/**
* Implements hook_block_info().
*/
function emh_profile_complete_expert_block_info() {
  $blocks['emh_profile_complete_expert'] = array(
    'info' => t('EMH Profile Complete - Expert'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 1,
    'region' => 'highlighted',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => "<front>\nmy-responses\nrequests/selection\nrequests\nnode/*",
  );

  return $blocks;
}

/**
* Implements hook_block_view().
*/
function emh_profile_complete_expert_block_view($delta = '') {
  global $user;
  $block = array();

  // No need to render a block for anonymous users.
  if (user_is_anonymous()) {
    return;
  }

  switch ($delta) {
    case 'emh_profile_complete_expert':

      $fields = emh_profile_complete_expert_set_fields();
      $out = emh_profile_complete_get_complete_percentage_data('user', 'user', $user, $fields);
      if ($out['incomplete'] == 0 || empty($out)) {
        $block['subject'] = '';
        $block['content'] = '';
      }
      else {
        $block['subject'] = t('Please complete the following information to access client requests');
        $block['content'] = array(
          '#markup' =>  _emh_profile_complete_expert_block_content(),
        );
      }

      break;
  }

  return $block;

}

function _emh_profile_complete_expert_block_content() {
  $fields = emh_profile_complete_expert_set_fields();
  $form = drupal_get_form('emh_profile_complete_expert_form', $fields);
  return drupal_render($form);
}

function emh_profile_complete_expert_set_fields() {
  $fields = array(
    'field_entreprise',
    'field_working_status',
    'field_domaine',
    'field_address',
  );
  return $fields;
}

function emh_profile_complete_expert_form($form, &$form_state, $fields) {

  global $user;
  $account = user_load($user->uid);
  $attach_form = array();

  $fields = _emh_profile_complete_get_empty_fields('user', 'user', $user, $fields);

  foreach ($fields as $field) {

    if (field_access('edit', $field, 'user')) {

      field_attach_form('user', $account, $attach_form, $form_state, NULL, array('field_name' => $field));
      $form[$field] = $attach_form[$field];

      switch ($field) {
        case 'field_address':
            $elements = $form['field_address'][LANGUAGE_NONE][0];
            $elements['#type'] = 'div';
            $elements['street_block']['thoroughfare']['#required'] = FALSE;
            $elements['street_block']['thoroughfare']['#access'] = FALSE;
            $elements['street_block']['premise']['#required'] = FALSE;
            $elements['street_block']['premise']['#access'] = FALSE;
            $elements['locality_block']['postal_code']['#required'] = FALSE;
            $elements['locality_block']['postal_code']['#access'] = FALSE;
            $elements['locality_block']['dependent_locality']['#required'] = FALSE;
            $elements['locality_block']['dependent_locality']['#access'] = FALSE;
            $elements['locality_block']['locality']['#required'] = FALSE;
            $elements['locality_block']['locality']['#access'] = FALSE;
            $elements['locality_block']['administrative_area']['#required'] = FALSE;
            $elements['locality_block']['administrative_area']['#access'] = FALSE;
            $elements['phone_block']['phone_number']['phone_number']['#required'] = FALSE;
            $elements['phone_block']['phone_number']['phone_number']['#access'] = FALSE;
            $elements['phone_block']['mobile_number']['#required'] = FALSE;
            $elements['phone_block']['mobile_number']['#access'] = FALSE;
            $form['field_address'][LANGUAGE_NONE][0] = $elements;
          break;

        default:
          break;
      }

    }
  }

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update your profile'),
    '#weight' => '100',
  );

  return $form;

}

function emh_profile_complete_expert_form_submit($form, &$form_state) {

  global $user;
  $account = user_load($user->uid);
  $edit = array();

  $fields = $form_state['build_info']['args'][0];
  $fields = _emh_profile_complete_get_empty_fields('user', 'user', $user, $fields);

  foreach ($fields as $field) {
    $field_name = $field;
    $edit[$field_name] = $form_state['values'][$field_name];
  }

  $edit = array_merge( $edit, array(
    'status' => 1,
    'access' => REQUEST_TIME,
  ) );

  user_save($account, $edit);

  drupal_set_message(t('Your profile has been updated. You have now access to client requests.'));

}
