<?php

/**
 * Implements hook_form_alter().
 */
function emh_honeypot_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_pass':
    case 'user_register_form_client':
    case 'user_register_form_expert':
    case 'contact_site_form':
      honeypot_add_form_protection($form, $form_state, array('honeypot', 'time_restriction'));
      break;
    default:
      break;
  }
}
