<?php

/**
 * @file
 * Provides a Bootstrap dropdown button to switch between available languages.
 */

/**
 * Implements hook_libraries_info().
 */
function bootstrap_languages_libraries_info() {
  $libraries['bootstrap-languages'] = array(
    'name' => 'Languages for Bootstrap 3',
    'vendor url' => 'http://usrz.github.io/bootstrap-languages/',
    'download url' => 'https://github.com/usrz/bootstrap-languages/archive/master.zip',
    'version' => '2.0',
    'files' => array(
      'css' => array('languages.min.css'),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_block_info().
 */
function bootstrap_languages_block_info() {
  include_once DRUPAL_ROOT . '/includes/language.inc';
  $block = array();
  $info = language_types_info();
  foreach (language_types_configurable(FALSE) as $type) {
    $block[$type] = array(
      'info' => t('Bootstrap Languages (@type)', array('@type' => $info[$type]['name'])),
      'cache' => DRUPAL_NO_CACHE,
    );
  }
  return $block;
}

/**
 * Implements hook_block_configure().
 */
function bootstrap_languages_block_configure($delta = '') {
  $settings = _bootstrap_languages_get_settings();
  $form = array();

  // Check if the Languages for Bootstrap 3 library is present.
  $library = libraries_load('bootstrap-languages');
  if ($library['loaded'] == FALSE) {
    drupal_set_message($library['error message'], 'error');
  }

  $form['bootstrap_languages'] = array(
    '#type' => 'fieldset',
    '#title' => t('Bootstrap Languages settings'),
    '#weight' => 0,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['bootstrap_languages']['showall'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show all enabled languages'),
    '#description' => t('Show all languages in the switcher no matter if there is a translation for the node or not. For languages without translation the switcher will redirect to homepage.'),
    '#default_value' => $settings['showall'],
  );
  $form['bootstrap_languages']['btntype'] = array(
    '#type' => 'select',
    '#title' => t('Bootstrap button type'),
    '#options' => array(
      'btn-default' => 'Default',
      'btn-primary' => 'Primary',
      'btn-info' => 'Info',
    ),
    '#default_value' => isset($settings['btntype']) ? $settings['btntype'] : 'btn-default',
  );
  return $form;
}

/**
 * Implements hook_block_save().
 */
function bootstrap_languages_block_save($delta = '', $edit = array()) {
  $bootstrap_languages_settings = array(
    'showall' => $edit['showall'],
    'btntype' => $edit['btntype'],
  );
  variable_set('bootstrap_languages', $bootstrap_languages_settings);
}

/**
 * Implements hook_block_view().
 */
function bootstrap_languages_block_view($type = 'language') {
  if (drupal_multilingual()) {
    $settings = _bootstrap_languages_get_settings();
    $module_path = drupal_get_path('module', 'bootstrap_languages');
    $options = array();
    $path = drupal_is_front_page() ? '<front>' : $_GET['q'];
    $languages = language_negotiation_get_switch_links($type, $path);

    // Load the Languages for Bootstrap 3 library.
    $library = libraries_load('bootstrap-languages');
    if (!$library['loaded']) {
      watchdog('Bootstrap Languages', $library['error message'], NULL, WATCHDOG_ERROR);
      return;
    }

    // Check if we should support Domain access
    if ($domain_locale_exists = module_exists('domain_locale')) {
      global $_domain;
      $domain_languages = domain_locale_lookup($_domain['domain_id']);
    }

    // Now we iterate on $languages to build needed options for dropdown.
    foreach ($languages->links as $lang_code => $lang_options) {
      // The language is not enabled on this domain
      if ($domain_locale_exists && !array_key_exists($lang_code, $domain_languages)) {
        continue;
      }

      // There is no translation for this language and not all languages are shown
      if (!isset($lang_options['href']) && (!$settings['showall'])) {
        continue;
      }

      // Build the options in an associative array (lang_code => lang_link)
      $href = isset($lang_options['href']) ? $lang_options['href'] : '<front>';
      $lang_link = check_plain(url($href, array(
        'language' => $lang_options['language'],
        'query' => isset($lang_options['query']) ? $lang_options['query'] : '',
      )));
      $options[$lang_code] = $lang_link;

      // Determine selected language option.
      if (isset($lang_options['href']) && ($lang_options['href'] == $_GET['q']
        || ($lang_options['href'] == '<front>' && drupal_is_front_page()))
        && ($lang_code == $GLOBALS[$type]->language)) {
        $selected_option = $lang_code;
      }
    }

    // Position language switcher to the right of the navbar.
    drupal_add_css($library['library path'] . '/languages.min.css');
    drupal_add_css($module_path . '/bootstrap_languages.css');

    // Build markup for the Bootstrap languages switcher.
    $default_option = isset($selected_option) ? $selected_option : $options[0];
    $markup = '<div class="btn-group">';
    $markup .= '  <button class="btn ' . $settings['btntype'] . ' btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">';
    $markup .= '    <span class="lang-sm" lang="' . $default_option . '"></span> <span class="caret"></span>';
    $markup .= '  </button>';
    $markup .= '  <ul class="dropdown-menu" role="menu">';
    foreach ($options as $lang_code => $lang_link) {
      $markup .= '    <li><a href="' . $lang_link . '"><span class="lang-sm lang-lbl" lang="' . $lang_code . '"></span></a></li>';
    }
    $markup .= '  </ul>';
    $markup .= '</div>';

    // Set the block subject and content
    if (isset($languages->links)) {
      $block['subject'] = t('Languages');
      $block['content'] = $markup;
      return $block;
    }
  }
}

/**
 * Helper function to get Bootstrap Languages settings
 */
function _bootstrap_languages_get_settings($settings = NULL) {
  $defaults = array(
    'showall' => 0,
  );
  return array_merge($defaults, variable_get('bootstrap_languages', $defaults));
}
