<?php
/**
* @file
* Code for eMindHub Landing Page feature.
*/

/*
 * Implements hook_forms().
 */
function emh_landing_page_forms($form_id, $args) {
  $forms = array();
  switch ($form_id) {
    case 'user_register_form_landing_page':
      $forms['user_register_form_landing_page'] = array (
        'callback' => 'user_register_form',
      );
      break;
    default:
      break;
  }
  return $forms;
}

/**
 * Implements hook_form_alter().
 */
function emh_landing_page_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_register_form_landing_page':
      return $form;
      break;
    default:
      break;
  }
}

function emh_landing_page_form_user_register_form_landing_page_alter(&$form, &$form_state, $form_id) {

  $form['field_first_name']['#prefix'] = '<div class="form-group-3col row">';
  $form['field_first_name'][LANGUAGE_NONE][0]['value']['#title_display'] = 'invisible';
  $form['field_first_name'][LANGUAGE_NONE][0]['value']['#attributes']['placeholder'] = $form['field_first_name'][LANGUAGE_NONE][0]['value']['#title'];

  $form['field_last_name'][LANGUAGE_NONE][0]['value']['#title_display'] = 'invisible';
  $form['field_last_name'][LANGUAGE_NONE][0]['value']['#attributes']['placeholder'] = $form['field_last_name'][LANGUAGE_NONE][0]['value']['#title'];
  $form['field_last_name']['#suffix'] = '</div>';

  $form['account']['#prefix'] = '<div class="account row">';
  $form['account']['mail']['#title_display'] = 'invisible';
  $form['account']['mail']['#attributes']['placeholder'] = $form['account']['mail']['#title'];
  $form['account']['mail']['#description'] = '';
  $form['account']['#suffix'] = '</div>';

  $form['actions']['submit']['#value'] = t('Start now');
  $form['actions']['submit']['#attributes']['class'][] = 'btn-success';

  $form['account']['pass']['#process'] = array('form_process_password_confirm', 'emh_landing_page_form_process_password_confirm');

  // Force Expert & Roleswitcher roles
  $form['account']['roles']['4'] = array(
    '#type' => 'checkbox',
    '#title' => 'expert',
    '#default_value' => TRUE,
    '#disabled' => TRUE,
  );
  $form['account']['roles']['10'] = array(
    '#type' => 'checkbox',
    '#title' => 'roleswitcher',
    '#default_value' => TRUE,
    '#disabled' => TRUE,
  );

  // echo '<pre>' . print_r($form, true) . '</pre>';

}

/**
 * Alter password and confirm password fields to remove title and insert placeholder.
 */
function emh_landing_page_form_process_password_confirm($element) {
  $element['pass1']['#title_display'] = "invisible";
  $element['pass1']['#attributes']['placeholder'] = t("Password");
  $element['pass2']['#title_display'] = "invisible";
  $element['pass2']['#attributes']['placeholder'] = t("Confirm password");
  return $element;
}

/**
 * Implements hook_block_info().
 */
function emh_landing_page_block_info() {
  $blocks = array();

  $blocks['landing_page_register'] = array(
    'info' => t('Landing page register form'),
  );

  return $blocks;
}

function emh_landing_page_block_view($delta = '') {
  $block = array();

  switch ($delta) {
  case 'landing_page_register':
    $block['subject'] = t('Landing page register form');
    $block['content'] = amh_landing_page_block_register_callback();
  }

  return $block;
}


function emh_landing_page_block_register_callback() {
  $reg_form = drupal_get_form('user_register_form_landing_page');
  $output = drupal_render($reg_form);
  return $output;
}
