<?php
/**
* @file
* Code for eMindHub Answer feature.
*/

/**
 * Implements hook_permission().
 */
function emh_answer_permission() {
  return array(
    'save comment draft' => array(
      'title' => t('Save comment as draft'),
      'description' => t('Allows a user to save a draft of their comment.'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
// function emh_answer_form_comment_form_alter(&$form, &$form_state) {
  // if (user_access('save comment draft')) {
  //   if (empty($form['#validate'])) {
  //     $form['#validate'] = array();
  //   }
  //   // array_unshift($form['#validate'], 'save_draft_validate');
  //   $form['actions']['draft'] = array(
  //     '#type' => 'submit',
  //     '#class' => 'form-submit',
  //     '#value' => t('Save as draft'),
  //     '#weight' => '9',
  //     '#submit' => array('_emh_answer_submit')
  //   );
  //   $form['actions']['submit']['#value'] = t('Publish');
  // }
// }

// function _emh_answer_submit($form, &$form_state) {
//   comment_form_submit($form, $form_state);
// }

/**
 * Implements hook_form_alter().
 */
function emh_answer_form_alter(&$form, &$form_state, $form_id) {

  if (isset($form['#node']->nid)) {
    $request_ID = $form['#node']->nid;
    switch ($form_id) {
      case "webform_client_form_$request_ID":
        if (!empty($form['#is_draft']) || empty($form['#submission'])) {
          $form['#submit'][] = '_emh_answer_form_submit';
        }
        break;
      case 'comment_node_question1_form':
      case 'comment_node_challenge_form':
        $form['#submit'][] = '_emh_answer_form_submit';
        break;
      default:
        break;
    }
  }

}

function _emh_answer_form_submit($form, &$form_state) {
  $node = $form['#node'];
  $author = user_load($node->uid);
  $module = 'emh_answer';
  $key = 'notify_request_author_new_answer';
  $mail = $author->mail;
  $language = language_default();
  switch ($node->type) {
    case 'question1':
    case 'challenge':
      $url = url('node/' . $node->nid . '/answers?pk_campaign=new_answer_' . $node->type . '_' . $node->nid, array('absolute' => TRUE));
      break;

    case 'webform':
      $url = url('node/' . $node->nid . '/results?pk_campaign=new_answer_' . $node->type . '_' . $node->nid, array('absolute' => TRUE));
      break;
    default:
      break;
  }
  $params = array(
    '@url' => $url,
    '@title' => $node->title,
    '@author' => $author->field_first_name[LANGUAGE_NONE][0]['value'],
  );

  drupal_mail($module, $key, $mail, $language, $params);
}

/**
 * Implements hook_mail().
 */
function emh_answer_mail($key, &$message, $params) {
  switch($key) {
    case 'notify_request_author_new_answer':
      $message['subject'] = t('New answer to the request @title', $params);
      $message['body'] = array();
      $message['body'][] = t('Dear @author,', $params);
      $message['body'][] = t('You received a new answer to the request') . ' <strong><a href="' . t('@url', $params) . '&amp;pk_kwd=link" title="' .  t('@title', $params) . '" target="_blank" style="font-weight:bold!important;">' . t('@title', $params) . ' </a></strong>';
      $message['body'][] = t('Just log into the platform to see this answer.');
      $message['body'][] = '<table style="min-width:100%;" width="100%" border="0" cellpadding="0" cellspacing="0" class="emailButton">
        <tbody>
          <tr>
            <td style="padding-top:0;padding-right:18px;padding-bottom:18px;padding-left:18px;" valign="top" align="center">
              <table style="border-collapse:separate!important;border-radius:0px;background-color:rgb(0,159,227);" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                  <tr>
                    <td style="font-family:Arial;font-size:16px;padding:15px;color:rgb(255, 255, 255);" valign="middle" align="center">
                      <a href="' . t('@url', $params) . '&amp;pk_kwd=calltoaction" title="' .  t('Log in to eMindHub') . '" target="_blank" style="font-weight:bold!important;letter-spacing:normal;line-height:100%;text-align:center;text-decoration:none;color:#FFFFFF!important;">' . t('Log in to eMindHub') . ' </a>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </tbody>
      </table>';
      break;
    default:
      break;
  }
}
