<?php
/**
 * @file
 * Code of the eMindHub request feature.
 */


include_once 'emh_request.deprecated.inc';
include_once 'emh_request.fields.inc';

define('OPT_BEHAVIOR_SHOW', 'show');
define('OPT_BEHAVIOR_HIDE', 'hide');


/**
 * Implements hook_hook_info().
 */
function emh_request_hook_info() {
  $hooks = array(
    'emh_request_option_info',
    'emh_request_option_info_alter',
    'emh_request_option_setting_form',
  );

  return array_fill_keys($hooks, array('group' => 'options'));
}


/**
 * Implements hook_node_info().
 */
function emh_request_node_info() {
  $content_types = array(
    'request' => array(
      'name' => t('Request'),
      'base' => 'node_content',
      'description' => 'Content type to address question(s) to the experts.',
      //'help' => '(optional) Help information shown to the user when creating a node of this type.',
      //'has_title' => '(optional) A Boolean indicating whether or not this node type has a title field.',
      //'title_label' => '(optional) The label for the title field of this content type.',
      'locked' => true,
    ),
  );

  drupal_alter('node_info', $content_types);
  return $content_types;
}


/**
 * Provides all available options.
 *
 * @return array Options definitions
 */
function emh_request_get_options() {
  $options = module_invoke_all('emh_request_option_info');
  drupal_alter('emh_request_option_info', $options);

  foreach ($options as &$option) {
    $option += emh_request_default_option_info();
  }

  return $options;
}


/**
 * Provides the option properties by default.
 *
 * @return array Option properties by default
 */
function emh_request_default_option_info() {
  return array(
    'cost' => 0,
    'weight' => 0,
    'behavior' => OPT_BEHAVIOR_HIDE,
  );
}
