<?php
/**
 * @file
 * Code of the eMindHub request feature.
 */


include_once 'emh_request.deprecated.inc';
include_once 'emh_request.fields.inc';

define('OPT_BEHAVIOR_SHOW', 'show');
define('OPT_BEHAVIOR_HIDE', 'hide');


/**
 * Implements hook_hook_info().
 */
function emh_request_hook_info() {
  $hooks = array(
    'emh_request_option_info',
    'emh_request_option_info_alter',
    'emh_request_option_setting_form',
  );

  return array_fill_keys($hooks, array('group' => 'options'));
}


/**
 * Provides all available options.
 *
 * @return array Options definitions
 */
function emh_request_get_options() {
  $options = module_invoke_all('emh_request_option_info');
  drupal_alter('emh_request_option_info', $options);

  foreach ($options as &$option) {
    $option += emh_request_default_option_info();
  }

  return $options;
}


/**
 * Provides the option properties by default.
 *
 * @return array Option properties by default
 */
function emh_request_default_option_info() {
  return array(
    'cost' => 0,
    'weight' => 0,
    'behavior' => OPT_BEHAVIOR_HIDE,
  );
}
