<?php
/**
* @file
* Code for eMindHub Question feature.
*/


/* Question hook form alter
 * node/add/question1
 * node/$ID/edit
 */
function emh_question_form_question1_node_form_alter(&$form, &$form_state, $form_id) {

	// echo '<pre>' . print_r($form, TRUE) . '</pre>';
	// echo '<pre>' . print_r($form_state, TRUE) . '</pre>';

  $form['field_reward'][LANGUAGE_NONE][0]['value']['#title'] = t('Cost');
  $form['field_reward'][LANGUAGE_NONE][0]['value']['#description'] = t('A minimum of !value points is required only if you have selected circle <i>All experts</i> or <i>Sponsors</i>.', array('!value' => variable_get('emh_points_question1_threshold', '100')));
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function emh_question_form_comment_node_question1_form_alter(&$form, &$form_state) {
  if (isset($form['#node']->field_force_public_answer) && !empty($form['#node']->field_force_public_answer)) {
    $form['field_private_comment'][LANGUAGE_NONE]['#default_value'] = '0';
    $form['field_private_comment']['#access'] = '0';
    $form['field_private_comment_body']['#access'] = '0';
  }
  $form['comment_body']['#states'] = array(
    'visible' => array(
      ':input[name="field_private_comment[und]"]' => array('value' => 0),
    ),
  );
  $form['field_private_comment_body']['#states'] = array(
    'visible' => array(
      ':input[name="field_private_comment[und]"]' => array('value' => 1),
    ),
  );
}
