<?php
/**
 * @file
 * Code for the eMindHub Question module installation.
 */

/**
 * Implements hook_enable
 */
function emh_question_enable() {
  emh_question_update_7001();
}

/**
 * Force module weight for hook_form_alter execution
 */
function emh_question_update_7001() {
  db_update('system')
  ->fields(array('weight' => 1))
  ->condition('type', 'module')
  ->condition('name', 'emh_question')
  ->execute();
}
