<?php
/**
* @file
* Code for eMindHub Question feature.
*/


/* Challenge hook form alter
 * node/add/question1
 * node/$ID/edit
 */
function emh_question_form_question1_node_form_alter(&$form, &$form_state, $form_id) {

	// echo '<pre>' . print_r($form['field_reward']['und'][0]['value'], TRUE) . '</pre>';
	// echo '<pre>' . print_r($form_state, TRUE) . '</pre>';

	// Add class before & after fields
  $form['field_domaine']['#prefix'] = '<div class="form-group-2col row">';
  $form['field_tags']['#suffix'] = '</div>';

  $form['field_anonymous']['#prefix'] = '<div class="form-group-3col row">';
  $form['field_use_my_entreprise']['#suffix'] = '</div>';

  $form['field_expiration_date']['#prefix'] = '<div class="form-group-2col row">';
  $form['field_reward']['und'][0]['value']['#title'] = t('Cost');
  $form['field_reward']['#suffix'] = '</div>';

  $form['og_group_ref']['#prefix'] = '<div class="form-group-2col row">';
  $form['field_other_members']['#suffix'] = '</div>';

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function emh_question_form_comment_node_question1_form_alter(&$form, &$form_state) {
  $form['comment_body']['#states'] = array(
    'visible' => array(
      ':input[name="field_private_comment[und]"]' => array('value' => 0),
    ),
  );
  $form['field_private_comment_body']['#states'] = array(
    'visible' => array(
      ':input[name="field_private_comment[und]"]' => array('value' => 1),
    ),
  );
}
